### ISSUE TITLE
Pokemon with no time returned from server generate multiple notifications

### ISSUE THREAD

**Issue by madmanic** [PokeAlert/PokeAlert#68]
After installing 2.3.8-7, Pokemon with no time returned from server get counted as a new instance of that Pokemon on every scan. This generates a new notification for that Pokemon each time the background scan runs (sometimes two if it falls in an area where steps overlap).

What lead me to this conclusion: This happened with an Eevee and Slowbro that spawned near me while I was background scanning in 1-minute intervals, Fast Scan disabled, and using 10 PTC accounts. I went to the location and caught them to confirm that only one copy spawned of each. On the PokeAlert map I removed them and found that there was a stack of each on the map, with expiration timers each about 1 minute apart. The changing timer is why I assume these were being returned from the server with no expiration time.

**Comment by TFD777** [comment]
![screenshot_2016-08-23-17-09-00](https://cloud.githubusercontent.com/assets/12085708/17895468/dc52cc6c-6955-11e6-9daa-aca621f2c812.png)
@PokeAlert  the problem occurs in the newest version 2.3.10-1 aswell.

**Comment by PokeAlert** [comment]
aaah!!! This is the problem then! Multiple people told me the same stuff but I was completrly unable to reproduce!

Thanks for this I will fix this asap

**Comment by PokeAlert** [comment]
@madmanic @TFD777 Actually could you guys comfirm that this is fixed in 2.3.11 and up ?
I had remove the timestamp in the key hashcode. so technically this bug no longer should be.

**Comment by TFD777** [comment]
@PokeAlert I didn't notice multiple notifications in the latest update. Everything is fine now. :+1:

**Comment by PokeAlert** [comment]
cool

**Comment by Eric678** [comment]
Still get 2nd notification when untimed mon changes to timed mon. 2.3.11-3.
Really should NOT put 15 mins in for untimed mon - BUG! Need to drop the mon if user has delete on timeout set when it is no long found in a scan.  Please spend more time testing - so many releases is very poor QA.
